os:
  - linux
dist: bionic
language: python
python:
  - "3.8"
jobs:
  include:
    - stage: Lint
      install:
        - pip3 install pycodestyle
      script: ./deploy/lint.sh
    - stage: Test
      script: echo "test"
    - stage: Build
      script: echo "build"
    - stage: Deploy
      script: echo "deploy"
