version: '3.5'

services:
  api:
    build: 
      context: .
      shm_size: 4gb
      dockerfile: ./api/Dockerfile
    command: ./init_api
    env_file:
      - ./.env.dev
    ports:
      - 8080:8080
    depends_on: 
      - db
    volumes:
      - browsers:/usr/src/app/api/browsers
  web:
    build: ./web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - 80:5000
    env_file:
      - ./.env.dev
    depends_on:
      - api
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=data_im_dev
      - POSTGRES_PASSWORD=dim_passwd
      - POSTGRES_DB=data_im_dev_db

volumes:
  postgres_data:
  browsers: