version: '3.7'

services:
  web:
    build: ./web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=data_im_dev
      - POSTGRES_PASSWORD=dim_passwd
      - POSTGRES_DB=data_im_dev_db

volumes:
  postgres_data: