version: '3.7'

services:
  api:
    build: 
      context: .
      shm_size: '4gb'
      dockerfile: ./api/Dockerfile.prod
    shm_size: '4gb'
    command: python3 -m api.v1.app
    env_file:
      - ./.env.prod
    ports:
      - 8080:8080
    depends_on: 
      - web
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/home/app/web/datainmotion/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    command: gunicorn -w 2 -b :8000 manage:app
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/datainmotion/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: